// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Zu0Wj5q9Wp-8-FTwTBqXQ_497TKPCY4',
    appId: '1:11675574656:web:b2e6182753883633ca6165',
    messagingSenderId: '11675574656',
    projectId: 'flutter-crud-app-example',
    authDomain: 'flutter-crud-app-example.firebaseapp.com',
    storageBucket: 'flutter-crud-app-example.appspot.com',
    measurementId: 'G-BT0DZVPPFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA24ukmWqLf3djPm2DINU3Uw0zBRvYeqGg',
    appId: '1:11675574656:android:d7efa56343ebb4b7ca6165',
    messagingSenderId: '11675574656',
    projectId: 'flutter-crud-app-example',
    storageBucket: 'flutter-crud-app-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL-6n5hYnroysTZJRdt7eD5aebPL3-_Is',
    appId: '1:11675574656:ios:eae7fe8853ac708cca6165',
    messagingSenderId: '11675574656',
    projectId: 'flutter-crud-app-example',
    storageBucket: 'flutter-crud-app-example.appspot.com',
    iosClientId: '11675574656-dv4iv1ije1esk8nbp2l18vj17teufcqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudApp',
  );
}
